;General
.define MT_UNKNOWN	$00,$00,$00,$00
.define MT_BLACK	$00,$00,$00,$00
.define MT_GRASS	$02,$02,$02,$02
.define MT_GRASSHDW	$02,$02,$02,$02
.define MT_FLOWERS	$02,$02,$02,$02
.define MT_TREES	$02,$02,$02,$02
.define MT_PATH		$05,$05,$05,$05
.define MT_DIRT		$05,$05,$05,$05
.define MT_DIRTSHDW	$05,$05,$05,$05
.define MT_ROCK		$04,$04,$04,$04
.define MT_METAL	$04,$04,$04,$04
.define MT_BRIDGE	$04,$04,$04,$04
.define MT_PONDWALL	$04,$04,$03,$03
.define MT_WATER	$03,$03,$03,$03
;World
.define MT_MOUNTAIN	$04,$04,$04,$04
.define MT_CLOUDS	$03,$03,$03,$03
.define MT_DUST		$05,$05,$05,$05
.define MT_CACTUS	$05,$05,$05,$05
.define MT_WEED		$05,$05,$05,$05
.define MT_PALMS	$05,$05,$05,$05
.define MT_TOWN		$05,$05,$05,$05
.define MT_CAVE		$05,$05,$05,$05
.define MT_SHRINE	$00,$00,$00,$00
.define MT_SHRINEW	$00,$00,$03,$03
.define MT_TOWER	$05,$05,$05,$05
.define MT_VINES	$02,$02,$02,$02
.define MT_LAVA		$01,$01,$01,$01
.define MT_MOON		$00,$00,$00,$00
;Town
.define MT_BRICK	$04,$04,$04,$04
.define MT_LAMP		$05,$05,$05,$05
.define MT_REDROOF	$01,$01,$01,$01
.define MT_DOOR		$04,$04,$04,$04
.define MT_HOUSEA	$00,$00,$00,$00
.define MT_HOUSEB	$05,$05,$05,$05
.define MT_HOUSEC	$04,$04,$04,$04
.define MT_SIGN		$00,$00,$00,$00
.define MT_CITY		$00,$00,$00,$00
.define MT_ROAD		$00,$00,$00,$00
.define MT_GLASS	$03,$03,$03,$03
;Town Interior
.define MT_FLOOR	$05,$05,$05,$05
.define MT_PLANT	$02,$02,$05,$05
.define MT_STAIRS	$00,$00,$00,$00
.define MT_WOOD		$04,$04,$04,$04
.define MT_BARREL	$04,$04,$04,$04
.define MT_OILDRUM	$04,$04,$04,$04
.define MT_POT		$05,$05,$05,$05
.define MT_COUNTER	$04,$04,$04,$04
.define MT_COUNTERS	$04,$04,$05,$05
.define MT_TABLE	$05,$05,$05,$05
.define MT_CHAIR	$05,$05,$05,$05
.define MT_STOOL	$05,$05,$05,$05
.define MT_WINDOW	$05,$05,$05,$05
.define MT_BLBOARD	$00,$00,$00,$00
.define MT_SHELF	$04,$04,$04,$04
.define MT_BED1		$04,$04,$01,$01
.define MT_BED2		$01,$01,$04,$04
.define MT_RECORD1	$05,$05,$05,$05
.define MT_RECORD2	$05,$05,$04,$04
.define MT_GARGOYLE	$00,$00,$00,$00
.define MT_MONITOR	$03,$03,$03,$03
;Dungeons
.define MT_SKY		$03,$03,$03,$03
.define MT_PASSAGE	$05,$05,$05,$05
.define MT_JAIL		$00,$00,$00,$00
;Shrine
.define MT_TILE		$00,$00,$00,$00
.define MT_KEYTILE	$03,$03,$03,$03
.define MT_STONE	$00,$00,$00,$00
.define MT_COLUMN	$00,$00,$00,$00
.define MT_STATUE	$00,$00,$00,$00
.define MT_STAGE	$00,$00,$00,$00
;Giant Town
.define MT_GWINDOW	$04,$04,$04,$04
.define MT_GBED1	$01,$01,$01,$01
.define MT_GBED2	$01,$01,$01,$01
.define	MT_GPILLOW1	$00,$04,$00,$04
.define MT_GPILLOW2 $00,$04,$04,$04
;Ki's Body
.define MT_BLOOD	$01,$01,$01,$01
.define MT_OOZE		$04,$04,$04,$04
.define MT_CELLS	$06,$06,$06,$06
;Vineworld
.define MT_CRYSTAL	$03,$03,$03,$03
.define MT_CRYSTALW	$03,$03,$03,$03
.define MT_STARSA	$01,$01,$01,$01
.define MT_STARSB	$00,$01,$02,$01

.BANK $17 SLOT 1
.SECTION "Metatile Attributes" FREE
MetatileAttr:
	;000 - First World Towns
	.db MT_GRASS,	MT_BLACK,	MT_REDROOF,	MT_DOOR,	MT_GRASS,	MT_PATH,	MT_BLACK,	MT_REDROOF
	.db MT_HOUSEA,	MT_BRICK,	MT_BRICK,	MT_BRICK,	MT_SIGN,	MT_SIGN,	MT_SIGN,	MT_SIGN
	.db MT_REDROOF,	MT_HOUSEB,	MT_GRASS,	MT_PATH,	MT_FLOWERS,	MT_TREES,	MT_TREES,	MT_TREES
	.db MT_BRIDGE,	MT_BRIDGE,	MT_BRIDGE,	MT_PONDWALL,MT_PONDWALL,MT_WATER,	MT_WATER,	MT_WATER
	;001 - Ashura's World Towns
	.db MT_DIRT,	MT_DIRT,	MT_DIRT,	MT_DOOR,	MT_GRASS,	MT_DIRT,	MT_GRASS,	MT_DIRTSHDW
	.db MT_DIRTSHDW,MT_BRICK,	MT_BRICK,	MT_BRICK,	MT_SIGN,	MT_SIGN,	MT_SIGN,	MT_SIGN
	.db MT_REDROOF,	MT_HOUSEB,	MT_GRASS,	MT_GRASS,	MT_GRASS,	MT_GRASS,	MT_GRASS,	MT_DIRTSHDW
	.db MT_DIRTSHDW,MT_BRIDGE,	MT_BRIDGE,	MT_BRIDGE,	MT_ROCK,	MT_ROCK,	MT_DIRT,	MT_DIRT
	;002 - First World, Ashura's World
	.db MT_MOUNTAIN,MT_DUST,	MT_DUST,	MT_TOWN,	MT_CAVE,	MT_SHRINE,	MT_SHRINE,	MT_SHRINE
	.db MT_VINES,	MT_TREES,	MT_DIRT,	MT_TOWER,	MT_SHRINEW,	MT_SHRINEW,	MT_VINES,	MT_VINES
	.db MT_SHRINE,	MT_GRASS,	MT_TREES,	MT_DIRT,	MT_DIRT,	MT_SHRINE,	MT_SHRINE,	MT_SHRINE
	.db MT_CACTUS,	MT_TOWER,	MT_TOWER,	MT_DUST,	MT_DUST,	MT_DUST,	MT_DUST,	MT_DUST
	;003 - Giant's World
	.db MT_MOUNTAIN,MT_MOON,	MT_MOON,	MT_TOWN,	MT_CAVE,	MT_ROCK,	MT_CAVE,	MT_VINES
	.db MT_VINES,	MT_VINES,	MT_STAIRS,	MT_DOOR,	MT_GWINDOW,	MT_GWINDOW,	MT_GWINDOW,	MT_ROCK
	.db MT_BRICK,	MT_GRASSHDW,MT_TREES,	MT_GRASS,	MT_REDROOF,	MT_GRASSHDW,MT_GRASS,	MT_GRASSHDW
	.db MT_GRASSHDW,MT_GRASS,	MT_GRASS,	MT_GRASS,	MT_GRASS,	MT_BRICK,	MT_BRICK,	MT_BLACK
	;004 - Apollo's World
	.db MT_MOUNTAIN,MT_MOUNTAIN,MT_WATER,	MT_TOWN,	MT_CAVE,	MT_SHRINE,	MT_CAVE,	MT_BRIDGE
	.db MT_VINES,	MT_VINES,	MT_VINES,	MT_GRASS,	MT_PONDWALL,MT_PONDWALL,MT_WATER,	MT_WATER
	.db MT_MOUNTAIN,MT_GRASS,	MT_TREES,	MT_DIRT,	MT_LAVA,	MT_SHRINE,	MT_SHRINE,	MT_SHRINE
	.db MT_SHRINE,	MT_DIRT,	MT_WEED,	MT_DIRT,	MT_DIRT,	MT_DIRT,	MT_DIRT,	MT_DIRT
	;005 - Guardian's World
	.db MT_MOUNTAIN,MT_BLACK,	MT_BLACK,	MT_DOOR,	MT_DOOR,	MT_VINES,	MT_VINES,	MT_VINES
	.db MT_WOOD,	MT_STONE,	MT_STONE,	MT_BRICK,	MT_SIGN,	MT_SIGN,	MT_SIGN,	MT_SIGN
	.db MT_MOUNTAIN,MT_DIRT,	MT_TREES,	MT_DIRT,	MT_REDROOF,	MT_HOUSEC,	MT_REDROOF,	MT_HOUSEC
	.db MT_STONE,	MT_STONE,	MT_BRICK,	MT_SIGN,	MT_SIGN,	MT_SIGN,	MT_SIGN,	MT_BLACK
	;006 - Venus' World
	.db MT_MOUNTAIN,MT_BLACK,	MT_BLACK,	MT_TOWN,	MT_ROAD,	MT_CAVE,	MT_VINES,	MT_METAL
	.db MT_METAL,	MT_CAVE,	MT_BLACK,	MT_BRICK,	MT_BRICK,	MT_BRICK,	MT_VINES,	MT_VINES
	.db MT_DIRT,	MT_ROAD,	MT_PALMS,	MT_PALMS,	MT_GRASS,	MT_CITY,	MT_CITY,	MT_TREES
	.db MT_ROAD,	MT_ROAD,	MT_DIRT,	MT_DIRT,	MT_DIRT,	MT_DIRT,	MT_ROAD,	MT_DUST
	;007
	.db MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_BLACK
	.db MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_BLACK
	.db MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_BLACK
	.db MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_BLACK
	;008
	.db MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_BLACK
	.db MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_BLACK
	.db MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_BLACK
	.db MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_BLACK
	;009
	.db MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_BLACK
	.db MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_BLACK
	.db MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_BLACK
	.db MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_BLACK
	;010 - Ki's Body
	.db MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_CAVE,	MT_BLOOD,	MT_BLACK,	MT_BLACK,	MT_BLACK
	.db MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_BLOOD,	MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_OOZE
	.db MT_OOZE,	MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_BLACK
	.db MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_CELLS,	MT_CELLS
	;011 - Town Interior
	.db MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_DOOR,	MT_DOOR,	MT_STAIRS,	MT_STAIRS,	MT_STAIRS
	.db MT_STAIRS,	MT_STAIRS,	MT_STAIRS,	MT_STAIRS,	MT_LAMP,	MT_DOOR,	MT_PLANT,	MT_BRICK
	.db MT_BRICK,	MT_BRICK,	MT_WOOD,	MT_FLOOR,	MT_BARREL,	MT_POT,		MT_SHELF,	MT_SHELF
	.db MT_BED1,	MT_BED2,	MT_TABLE,	MT_CHAIR,	MT_TABLE,	MT_CHAIR,	MT_WINDOW,	MT_BLACK
	;012 - Mr. S' School
	.db MT_BLACK,	MT_BLACK,	MT_WOOD,	MT_DOOR,	MT_DOOR,	MT_STAIRS,	MT_STAIRS,	MT_STAIRS
	.db MT_STAIRS,	MT_STAIRS,	MT_STAIRS,	MT_STAIRS,	MT_STAIRS,	MT_TABLE,	MT_CHAIR,	MT_WOOD
	.db MT_WOOD,	MT_WOOD,	MT_BLACK,	MT_FLOOR,	MT_DIRT,	MT_POT,		MT_SHELF,	MT_SHELF
	.db MT_BED1,	MT_BED2,	MT_BLBOARD,	MT_BLBOARD,	MT_TABLE,	MT_CHAIR,	MT_PLANT,	MT_BLACK
	;013 - Cave
	.db MT_ROCK,	MT_ROCK,	MT_ROCK,	MT_SKY,		MT_ROCK,	MT_GRASS,	MT_GRASS,	MT_STAIRS
	.db MT_STAIRS,	MT_STAIRS,	MT_STAIRS,	MT_STAIRS,	MT_STAIRS,	MT_GRASSHDW,MT_BRIDGE,	MT_ROCK
	.db MT_ROCK,	MT_ROCK,	MT_GRASSHDW,MT_SKY,		MT_GRASS,	MT_GRASS,	MT_GRASS,	MT_GRASS
	.db MT_GRASS,	MT_GRASSHDW,MT_GRASSHDW,MT_PASSAGE,	MT_PASSAGE,	MT_DOOR,	MT_BRIDGE,	MT_BLACK
	;014 - Another Town
	.db MT_GRASS,	MT_BLACK,	MT_BLACK,	MT_DOOR,	MT_GRASS,	MT_STONE,	MT_HOUSEA,	MT_BRIDGE
	.db MT_BRICK,	MT_BRICK,	MT_BRICK,	MT_REDROOF,	MT_SIGN,	MT_SIGN,	MT_SIGN,	MT_SIGN
	.db MT_REDROOF,	MT_HOUSEC,	MT_GRASS,	MT_STONE,	MT_FLOWERS,	MT_TREES,	MT_TREES,	MT_TREES
	.db MT_GRASS,	MT_BRIDGE,	MT_BRIDGE,	MT_PONDWALL,MT_PONDWALL,MT_WATER,	MT_WATER,	MT_WATER
	;015 - Giant Room
	.db MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_CAVE,	MT_BLACK,	MT_BLACK,	MT_UNKNOWN,	MT_REDROOF
	.db MT_REDROOF,	MT_REDROOF,	MT_UNKNOWN,	MT_GWINDOW,	MT_GBED1,	MT_GBED2,	MT_GPILLOW1,MT_GPILLOW2
	.db MT_TILE,	MT_TILE,	MT_GWINDOW,	MT_GWINDOW,	MT_WOOD,	MT_WOOD,	MT_WOOD,	MT_WOOD
	.db MT_WOOD,	MT_WOOD,	MT_BLACK,	MT_BLACK,	MT_BRICK,	MT_BRICK,	MT_BRICK,	MT_BLACK
	;016 - Shop Interior
	.db MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_DOOR,	MT_DOOR,	MT_FLOOR,	MT_FLOOR,	MT_SHELF
	.db MT_COUNTERS,MT_SHELF,	MT_SHELF,	MT_LAMP,	MT_SIGN,	MT_SIGN,	MT_SIGN,	MT_BRICK
	.db MT_BRICK,	MT_BRICK,	MT_WOOD,	MT_FLOOR,	MT_DOOR,	MT_DOOR,	MT_TABLE,	MT_CHAIR
	.db MT_PLANT,	MT_BED1,	MT_BED2,	MT_COUNTER,	MT_COUNTERS,MT_POT,		MT_BARREL,	MT_BLACK
	;017 - Pub Interior
	.db MT_BLACK,	MT_BLACK,	MT_BRICK,	MT_DOOR,	MT_DOOR,	MT_FLOOR,	MT_FLOOR,	MT_SHELF
	.db MT_COUNTERS,MT_BLACK,	MT_SHELF,	MT_SHELF,	MT_LAMP,	MT_POT,		MT_BARREL,	MT_BRICK
	.db MT_BRICK,	MT_BRICK,	MT_WOOD,	MT_FLOOR,	MT_DOOR,	MT_DOOR,	MT_TABLE,	MT_CHAIR
	.db MT_PLANT,	MT_STAIRS,	MT_STAIRS,	MT_COUNTER,	MT_COUNTERS,MT_RECORD1,	MT_RECORD2,	MT_BLACK
	;018 - Giant Store
	.db MT_BLACK,	MT_BLACK,	MT_BRICK,	MT_DOOR,	MT_DOOR,	MT_FLOOR,	MT_FLOOR,	MT_SHELF
	.db MT_COUNTERS,MT_SHELF,	MT_SHELF,	MT_LAMP,	MT_PLANT,	MT_POT,		MT_BARREL,	MT_BRICK
	.db MT_BRICK,	MT_BRICK,	MT_WOOD,	MT_FLOOR,	MT_DOOR,	MT_DOOR,	MT_TABLE,	MT_CHAIR
	.db MT_BLACK,	MT_BED1,	MT_BED2,	MT_COUNTER,	MT_COUNTERS,MT_TABLE,	MT_CHAIR,	MT_BLACK
	;019 - Ki's Shrine
	.db MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_TILE,	MT_STAIRS,	MT_STAIRS,	MT_STAIRS,	MT_STAIRS
	.db MT_STAIRS,	MT_STAIRS,	MT_STAIRS,	MT_STAIRS,	MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_STONE
	.db MT_STONE,	MT_COLUMN,	MT_COLUMN,	MT_TILE,	MT_STATUE,	MT_STATUE,	MT_COLUMN,	MT_COLUMN
	.db MT_KEYTILE,	MT_KEYTILE,	MT_KEYTILE,	MT_KEYTILE,	MT_BLACK,	MT_STAGE,	MT_STAGE,	MT_BLACK
	;020 - Forest Tower Exterior
	.db MT_TREES,	MT_BLACK,	MT_BLACK,	MT_GRASS,	MT_BLACK,	MT_STAIRS,	MT_STAIRS,	MT_STAIRS
	.db MT_STAIRS,	MT_STAIRS,	MT_STAIRS,	MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_BLACK
	.db MT_BRICK,	MT_BRICK,	MT_BRICK,	MT_TILE,	MT_DIRT,	MT_TREES,	MT_TREES,	MT_TREES
	.db MT_FLOOR,	MT_COLUMN,	MT_COLUMN,	MT_GRASS,	MT_TILE,	MT_GRASSHDW,MT_GRASSHDW,MT_BLACK
	;021 - Forest Tower Interior
	.db MT_BLACK,	MT_BLACK,	MT_BRICK,	MT_TILE,	MT_DOOR,	MT_DOOR,	MT_STAIRS,	MT_STAIRS
	.db MT_STAIRS,	MT_STAIRS,	MT_STAIRS,	MT_STAIRS,	MT_STAIRS,	MT_STAIRS,	MT_BLACK,	MT_BRICK
	.db MT_BRICK,	MT_BRICK,	MT_BRICK,	MT_TILE,	MT_DOOR,	MT_DOOR,	MT_PASSAGE,	MT_PASSAGE
	.db MT_FLOOR,	MT_COLUMN,	MT_COLUMN,	MT_BLACK,	MT_BLACK,	MT_GRASSHDW,MT_GRASSHDW,MT_BLACK
	;022 - Forest Tower Interior
	.db MT_BLACK,	MT_BLACK,	MT_BRICK,	MT_DOOR,	MT_DOOR,	MT_STAIRS,	MT_STAIRS,	MT_STAIRS
	.db MT_STAIRS,	MT_STAIRS,	MT_STAIRS,	MT_PASSAGE,	MT_PASSAGE,	MT_OILDRUM,	MT_GARGOYLE,MT_BRICK
	.db MT_BRICK,	MT_BRICK,	MT_BRICK,	MT_FLOOR,	MT_DOOR,	MT_DOOR,	MT_BRICK,	MT_BARREL
	.db MT_TABLE,	MT_CHAIR,	MT_TABLE,	MT_CHAIR,	MT_COUNTER,	MT_COUNTERS,MT_MONITOR,	MT_MONITOR
	;023 - Ashura's Tower
	.db MT_BLACK,	MT_BLACK,	MT_BRICK,	MT_DOOR,	MT_DOOR,	MT_TILE,	MT_STAIRS,	MT_STAIRS
	.db MT_STAIRS,	MT_STAIRS,	MT_STAIRS,	MT_STAIRS,	MT_PASSAGE,	MT_PASSAGE,	MT_BRICK,	MT_BRICK
	.db MT_BRICK,	MT_BRICK,	MT_BRICK,	MT_TILE,	MT_DOOR,	MT_DOOR,	MT_COLUMN,	MT_COLUMN
	.db MT_FLOOR,	MT_SHELF,	MT_SHELF,	MT_JAIL,	MT_STAIRS,	MT_STAIRS,	MT_STAIRS,	MT_DIRT
	;024
	.db MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_BLACK
	.db MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_BLACK
	.db MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_BLACK
	.db MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_BLACK
	;025
	.db MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_BLACK
	.db MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_BLACK
	.db MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_BLACK
	.db MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_BLACK
	;026
	.db MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_BLACK
	.db MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_BLACK
	.db MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_BLACK
	.db MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_BLACK
	;027
	.db MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_BLACK
	.db MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_BLACK
	.db MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_BLACK
	.db MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_BLACK
	;028
	.db MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_BLACK
	.db MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_BLACK
	.db MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_BLACK
	.db MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_BLACK
	;029
	.db MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_BLACK
	.db MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_BLACK
	.db MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_BLACK
	.db MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_BLACK
	;030
	.db MT_BLACK,	MT_BLACK,	MT_METAL,	MT_FLOOR,	MT_DOOR,	MT_DOOR,	MT_STAIRS,	MT_STAIRS
	.db MT_STAIRS,	MT_STAIRS,	MT_STAIRS,	MT_STAIRS,	MT_STAIRS,	MT_STAIRS,	MT_JAIL,	MT_METAL
	.db MT_METAL,	MT_METAL,	MT_FLOOR,	MT_FLOOR,	MT_DOOR,	MT_DOOR,	MT_METAL,	MT_OILDRUM
	.db MT_STOOL,	MT_TABLE,	MT_BED1,	MT_BED2,	MT_COUNTER,	MT_COUNTERS,MT_MONITOR,	MT_MONITOR
	;031
	.db MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_BLACK
	.db MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_BLACK
	.db MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_BLACK
	.db MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_BLACK
	;032
	.db MT_BLACK,	MT_BLACK,	MT_WOOD,	MT_DOOR,	MT_DOOR,	MT_FLOOR,	MT_FLOOR,	MT_SHELF
	.db MT_COUNTERS,MT_STAIRS,	MT_SHELF,	MT_SHELF,	MT_LAMP,	MT_FLOOR,	MT_FLOOR,	MT_WOOD
	.db MT_WOOD,	MT_WOOD,	MT_WOOD,	MT_FLOOR,	MT_DOOR,	MT_DOOR,	MT_TABLE,	MT_FLOOR
	.db MT_FLOOR,	MT_STAIRS,	MT_STAIRS,	MT_WOOD,	MT_COUNTERS,MT_RECORD1,	MT_RECORD2,	MT_BLACK
	;033
	.db MT_CITY,	MT_BLACK,	MT_BLACK,	MT_CITY,	MT_BLACK,	MT_GLASS,	MT_GLASS,	MT_GLASS
	.db MT_GLASS,	MT_CITY,	MT_CITY,	MT_CITY,	MT_BRICK,	MT_BRICK,	MT_CITY,	MT_TREES
	.db MT_CITY,	MT_CITY,	MT_CITY,	MT_ROAD,	MT_GLASS,	MT_GLASS,	MT_CITY,	MT_ROAD
	.db MT_ROAD,	MT_ROAD,	MT_ROAD,	MT_ROAD,	MT_ROAD,	MT_ROAD,	MT_BRIDGE,	MT_BRIDGE
	;034
	.db MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_BLACK
	.db MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_BLACK
	.db MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_BLACK
	.db MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_BLACK
	;035
	.db MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_BLACK
	.db MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_BLACK
	.db MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_BLACK
	.db MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_BLACK
	;036
	.db MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_BLACK
	.db MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_BLACK
	.db MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_BLACK
	.db MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_BLACK
	;037
	.db MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_BLACK
	.db MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_BLACK
	.db MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_BLACK
	.db MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_BLACK
	;038
	.db MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_BLACK
	.db MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_BLACK
	.db MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_BLACK
	.db MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_BLACK
	;039
	.db MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_BLACK
	.db MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_BLACK
	.db MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_BLACK
	.db MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_BLACK
	;040 - Apollo's Shrine
	.db MT_BLACK,	MT_BLACK,	MT_LAMP,	MT_STAIRS,	MT_STAIRS,	MT_STAIRS,	MT_STAIRS,	MT_STAIRS
	.db MT_STAIRS,	MT_STAIRS,	MT_STAIRS,	MT_STAIRS,	MT_BLACK,	MT_WOOD,	MT_WOOD,	MT_LAMP
	.db MT_LAMP,	MT_COLUMN,	MT_COLUMN,	MT_TILE,	MT_TILE,	MT_PASSAGE,	MT_COLUMN,	MT_COLUMN
	.db MT_TILE,	MT_TILE,	MT_TILE,	MT_TILE,	MT_PASSAGE,	MT_STAGE,	MT_STAGE,	MT_BLACK
	;041
	.db MT_ROCK,	MT_ROCK,	MT_ROCK,	MT_SKY,		MT_STAIRS,	MT_STAIRS,	MT_STAIRS,	MT_STAIRS
	.db MT_STAIRS,	MT_STAIRS,	MT_STAIRS,	MT_STAIRS,	MT_SKY,		MT_BRIDGE,	MT_BRIDGE,	MT_ROCK
	.db MT_ROCK,	MT_ROCK,	MT_ROCK,	MT_DIRT,	MT_DIRTSHDW,MT_DIRTSHDW,MT_BLACK,	MT_BLACK
	.db MT_BLACK,	MT_DIRTSHDW,MT_PASSAGE,	MT_PASSAGE,	MT_DIRTSHDW,MT_ROCK,	MT_CAVE,	MT_BLACK
	;042 - Undersea Volcano
	.db MT_BLACK,	MT_BLACK,	MT_ROCK,	MT_SKY,		MT_ROCK,	MT_DIRT,	MT_CAVE,	MT_ROCK
	.db MT_ROCK,	MT_ROCK,	MT_ROCK,	MT_ROCK,	MT_ROCK,	MT_ROCK,	MT_ROCK,	MT_ROCK
	.db MT_ROCK,	MT_ROCK,	MT_ROCK,	MT_SKY,		MT_DIRT,	MT_LAVA,	MT_BLACK,	MT_PASSAGE
	.db MT_PASSAGE,	MT_ROCK,	MT_CAVE,	MT_ROCK,	MT_CAVE,	MT_STONE,	MT_STONE,	MT_LAVA
	;043 - Unused map?
	.db MT_BLACK,	MT_BLACK,	MT_CRYSTAL,	MT_SKY,		MT_CRYSTAL,	MT_BLACK,	MT_CAVE,	MT_STAIRS
	.db MT_STAIRS,	MT_STAIRS,	MT_STAIRS,	MT_STAIRS,	MT_STAIRS,	MT_STAIRS,	MT_STAIRS,	MT_CRYSTAL
	.db MT_CRYSTAL,	MT_CRYSTAL,	MT_MOON,	MT_SKY,		MT_BRIDGE,	MT_BRIDGE,	MT_PASSAGE,	MT_PASSAGE
	.db MT_MOON,	MT_BLACK,	MT_MOON,	MT_MOON,	MT_CRYSTAL,	MT_CAVE,	MT_BLACK,	MT_BLACK
	;044 - Unused map?
	.db MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_SKY,		MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_BLACK
	.db MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_SKY,		MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_BLACK
	.db MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_BLACK
	.db MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_BLACK
	;045
	.db MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_BLACK
	.db MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_BLACK
	.db MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_BLACK
	.db MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_BLACK
	;046
	.db MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_BLACK
	.db MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_BLACK
	.db MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_BLACK
	.db MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_BLACK
	;047
	.db MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_BLACK
	.db MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_BLACK
	.db MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_BLACK
	.db MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_BLACK
	;048
	.db MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_BLACK
	.db MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_BLACK
	.db MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_BLACK
	.db MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_BLACK
	;049
	.db MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_BLACK
	.db MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_BLACK
	.db MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_BLACK
	.db MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_BLACK
	;050
	.db MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_BLACK
	.db MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_BLACK
	.db MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_BLACK
	.db MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_BLACK
	;051
	.db MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_BLACK
	.db MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_BLACK
	.db MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_BLACK
	.db MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_BLACK
	;052
	.db MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_BLACK
	.db MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_BLACK
	.db MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_BLACK
	.db MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_BLACK
	;053
	.db MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_BLACK
	.db MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_BLACK
	.db MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_BLACK
	.db MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_BLACK
	;054
	.db MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_BLACK
	.db MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_BLACK
	.db MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_BLACK
	.db MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_BLACK
	;055
	.db MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_BLACK
	.db MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_BLACK
	.db MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_BLACK
	.db MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_BLACK
	;056
	.db MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_BLACK
	.db MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_BLACK
	.db MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_BLACK
	.db MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_BLACK
	;057
	.db MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_BLACK
	.db MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_BLACK
	.db MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_BLACK
	.db MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_BLACK
	;058 - Vineworld
	.db MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_DOOR,	MT_DOOR,	MT_CRYSTALW,MT_CRYSTAL,	MT_STAIRS
	.db MT_STAIRS,	MT_STAIRS,	MT_STAIRS,	MT_BLACK,	MT_CRYSTAL,	MT_STARSA,	MT_STARSB,	MT_SIGN
	.db MT_SIGN,	MT_SIGN,	MT_STAGE,	MT_STAGE,	MT_DOOR,	MT_DOOR,	MT_BLACK,	MT_BLACK
	.db MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_BLACK
	;059 - Vineworld
	.db MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_VINES,	MT_STAGE,	MT_SHRINE,	MT_BLACK,	MT_BLACK
	.db MT_BLACK,	MT_BLACK,	MT_ROCK,	MT_ROCK,	MT_CRYSTAL,	MT_BRIDGE,	MT_BRIDGE,	MT_BRIDGE
	.db MT_VINES,	MT_VINES,	MT_VINES,	MT_VINES,	MT_SHRINE,	MT_SHRINE,	MT_SHRINE,	MT_SHRINE
	.db MT_SHRINE,	MT_SHRINE,	MT_BLACK,	MT_BLACK,	MT_SHRINE,	MT_SHRINE,	MT_BLACK,	MT_STARSB
	;060
	.db MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_BLACK
	.db MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_BLACK
	.db MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_BLACK
	.db MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_BLACK
	;061
	.db MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_BLACK
	.db MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_BLACK
	.db MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_BLACK
	.db MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_BLACK
	;062
	.db MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_BLACK
	.db MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_BLACK
	.db MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_BLACK
	.db MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_BLACK
	;063
	.db MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_BLACK
	.db MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_BLACK
	.db MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_BLACK
	.db MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_BLACK
MetatileAttrEnd:
.ENDS

