;General
.define MT_UNKNOWN	$00,$00,$00,$00
.define MT_BLACK	$00,$00,$00,$00
.define MT_GRASS	$02,$02,$02,$02
.define MT_GRASSHDW	$02,$02,$02,$02
.define MT_FLOWERS	$02,$02,$02,$02
.define MT_TREES	$02,$02,$02,$02
.define MT_PATH		$05,$05,$05,$05
.define MT_DIRT		$05,$05,$05,$05
.define MT_DIRTSHDW	$05,$05,$05,$05
.define MT_ROCK		$04,$04,$04,$04
.define MT_METAL	$04,$04,$04,$04
.define MT_BRIDGE	$04,$04,$04,$04
.define MT_PONDWALL	$04,$04,$03,$03
.define MT_WATER	$03,$03,$03,$03
;World
.define MT_MOUNTAIN	$04,$04,$04,$04
.define MT_CLOUDS	$03,$03,$03,$03
.define MT_DUST		$05,$05,$05,$05
.define MT_CACTUS	$05,$05,$05,$05
.define MT_WEED		$05,$05,$05,$05
.define MT_PALMS	$02,$02,$02,$02
.define MT_PALM		$02,$02,$05,$05
.define MT_TOWN		$05,$05,$05,$05
.define MT_CAVE		$05,$05,$05,$05
.define MT_SHRINE	$00,$00,$00,$00
.define MT_SHRINEW	$00,$00,$03,$03
.define MT_TOWER	$05,$05,$05,$05
.define MT_VINES	$02,$02,$02,$02
.define MT_VOLCANOT	$05,$05,$01,$01
.define MT_VOLCANOL	$05,$05,$05,$05
.define MT_VOLCANOR	$05,$05,$05,$05
.define MT_VOLCANO	$05,$05,$05,$05
.define MT_LAVA		$01,$01,$01,$01
.define MT_MOON		$00,$00,$00,$00
.define MT_SHOGUN1	$05,$04,$04,$04
.define MT_SHOGUN2	$04,$05,$04,$04
;Town
.define MT_BRICK	$04,$04,$04,$04
.define MT_LAMP		$05,$05,$05,$05
.define MT_REDROOF	$01,$01,$01,$01
.define MT_DOOR		$04,$04,$04,$04
.define MT_HOUSEA	$00,$00,$00,$00
.define MT_HOUSEB	$05,$05,$05,$05
.define MT_HOUSEC	$04,$04,$04,$04
.define MT_SIGN		$00,$00,$00,$00
.define MT_CITY		$00,$00,$00,$00
.define MT_ROAD		$00,$00,$00,$00
.define MT_GLASS	$03,$03,$03,$03
.define MT_FENCE	$04,$04,$04,$04
.define MT_SUPPORTG	$04,$04,$02,$02
.define MT_SUPPORTD $04,$04,$05,$05
;Town Interior
.define MT_FLOOR	$05,$05,$05,$05
.define MT_TATAMI	$05,$05,$05,$05
.define MT_PLANT	$02,$02,$05,$05
.define MT_STAIRS	$00,$00,$00,$00
.define MT_WOOD		$04,$04,$04,$04
.define MT_BLOCK	$04,$04,$04,$04
.define MT_BARREL	$04,$04,$04,$04
.define MT_OILDRUM	$04,$04,$04,$04
.define MT_POT		$05,$05,$05,$05
.define MT_COUNTER	$04,$04,$04,$04
.define MT_COUNTERS	$04,$04,$05,$05
.define MT_TABLE	$05,$05,$05,$05
.define MT_CHAIR	$05,$05,$05,$05
.define MT_STOOL	$05,$05,$05,$05
.define MT_WINDOW	$05,$05,$05,$05
.define MT_BLBOARD	$00,$00,$00,$00
.define MT_SHELF	$04,$04,$04,$04
.define MT_BED1		$04,$04,$01,$01
.define MT_BED2		$01,$01,$04,$04
.define MT_BEDB1	$00,$00,$01,$01
.define MT_BEDB2	$01,$01,$01,$01
.define MT_RECORD1	$05,$05,$05,$05
.define MT_RECORD2	$05,$05,$04,$04
.define MT_GARGOYLE	$00,$00,$00,$00
.define MT_MONITOR	$03,$03,$03,$03
.define MT_STWALL	$00,$00,$04,$04
.define MT_STWALL2	$04,$04,$00,$00
;Dungeons
.define MT_SKY		$03,$03,$03,$03
.define MT_PASSAGE	$05,$05,$05,$05
.define MT_JAIL		$00,$00,$00,$00
.define MT_CORNERA	$05,$05,$05,$04
.define MT_CORNERB	$05,$05,$04,$05
;Shrine
.define MT_TILE		$00,$00,$00,$00
.define MT_KEYTILE	$03,$03,$03,$03
.define MT_STONE	$00,$00,$00,$00
.define MT_COLUMN	$00,$00,$00,$00
.define MT_STATUE	$00,$00,$00,$00
.define MT_STAGE	$00,$00,$00,$00
;Giant Town
.define MT_GWINDOW	$04,$04,$04,$04
.define MT_GBED1	$01,$01,$01,$01
.define MT_GBED2	$01,$01,$01,$01
.define	MT_GPILLOW1	$00,$04,$00,$04
.define MT_GPILLOW2 $00,$04,$04,$04
;Ki's Body
.define MT_BLOOD	$01,$01,$01,$01
.define MT_OOZE		$04,$04,$04,$04
.define MT_CELLS	$06,$06,$06,$06
;Vineworld
.define MT_CRYSTAL	$03,$03,$03,$03
.define MT_CRYSTALW	$03,$03,$03,$03
.define MT_STARSA	$01,$01,$01,$01
.define MT_STARSB	$00,$01,$02,$01

.BANK $17 SLOT 1
.SECTION "Metatile Attributes" FREE
MetatileAttr:
	;000 - First World Towns
	.db MT_GRASS,	MT_BLACK,	MT_REDROOF,	MT_DOOR,	MT_GRASS,	MT_PATH,	MT_BLACK,	MT_REDROOF
	.db MT_HOUSEA,	MT_BRICK,	MT_BRICK,	MT_BRICK,	MT_SIGN,	MT_SIGN,	MT_SIGN,	MT_SIGN
	.db MT_REDROOF,	MT_HOUSEB,	MT_GRASS,	MT_PATH,	MT_FLOWERS,	MT_TREES,	MT_TREES,	MT_TREES
	.db MT_BRIDGE,	MT_BRIDGE,	MT_BRIDGE,	MT_PONDWALL,MT_PONDWALL,MT_WATER,	MT_WATER,	MT_WATER
	;001 - Ashura's World Towns
	.db MT_DIRT,	MT_DIRT,	MT_DIRT,	MT_DOOR,	MT_GRASS,	MT_DIRT,	MT_GRASS,	MT_DIRTSHDW
	.db MT_DIRTSHDW,MT_BRICK,	MT_BRICK,	MT_BRICK,	MT_SIGN,	MT_SIGN,	MT_SIGN,	MT_SIGN
	.db MT_REDROOF,	MT_HOUSEB,	MT_GRASS,	MT_GRASS,	MT_GRASS,	MT_GRASS,	MT_GRASS,	MT_DIRTSHDW
	.db MT_DIRTSHDW,MT_BRIDGE,	MT_BRIDGE,	MT_BRIDGE,	MT_ROCK,	MT_ROCK,	MT_DIRT,	MT_DIRT
	;002 - First World, Ashura's World, Nasty World, Final World
	.db MT_MOUNTAIN,MT_DUST,	MT_DUST,	MT_TOWN,	MT_CAVE,	MT_SHRINE,	MT_SHRINE,	MT_SHRINE
	.db MT_VINES,	MT_TREES,	MT_DIRT,	MT_TOWER,	MT_SHRINEW,	MT_SHRINEW,	MT_VINES,	MT_VINES
	.db MT_SHRINE,	MT_GRASS,	MT_TREES,	MT_DIRT,	MT_DIRT,	MT_SHRINE,	MT_SHRINE,	MT_SHRINE
	.db MT_CACTUS,	MT_TOWER,	MT_TOWER,	MT_DUST,	MT_DUST,	MT_DUST,	MT_DUST,	MT_DUST
	;003 - Giant's World
	.db MT_MOUNTAIN,MT_MOON,	MT_MOON,	MT_TOWN,	MT_CAVE,	MT_ROCK,	MT_CAVE,	MT_VINES
	.db MT_VINES,	MT_VINES,	MT_STAIRS,	MT_DOOR,	MT_GWINDOW,	MT_GWINDOW,	MT_GWINDOW,	MT_ROCK
	.db MT_BRICK,	MT_GRASSHDW,MT_TREES,	MT_GRASS,	MT_REDROOF,	MT_GRASSHDW,MT_GRASS,	MT_GRASSHDW
	.db MT_GRASSHDW,MT_GRASS,	MT_GRASS,	MT_GRASS,	MT_GRASS,	MT_BRICK,	MT_BRICK,	MT_BLACK
	;004 - Apollo's World
	.db MT_MOUNTAIN,MT_MOUNTAIN,MT_WATER,	MT_TOWN,	MT_CAVE,	MT_SHRINE,	MT_CAVE,	MT_BRIDGE
	.db MT_VINES,	MT_VINES,	MT_VINES,	MT_GRASS,	MT_PONDWALL,MT_PONDWALL,MT_WATER,	MT_WATER
	.db MT_MOUNTAIN,MT_GRASS,	MT_TREES,	MT_DIRT,	MT_LAVA,	MT_SHRINE,	MT_SHRINE,	MT_SHRINE
	.db MT_SHRINE,	MT_DIRT,	MT_WEED,	MT_VOLCANOT,MT_VOLCANO,	MT_VOLCANOL,MT_VOLCANOR,MT_DIRT
	;005 - Guardian's World
	.db MT_MOUNTAIN,MT_BLACK,	MT_BLACK,	MT_DOOR,	MT_DOOR,	MT_VINES,	MT_VINES,	MT_VINES
	.db MT_REDROOF,	MT_STONE,	MT_STONE,	MT_BRICK,	MT_SIGN,	MT_SIGN,	MT_SIGN,	MT_SIGN
	.db MT_MOUNTAIN,MT_DIRT,	MT_TREES,	MT_DIRT,	MT_REDROOF,	MT_HOUSEC,	MT_REDROOF,	MT_HOUSEC
	.db MT_STONE,	MT_STONE,	MT_BRICK,	MT_SIGN,	MT_SIGN,	MT_SIGN,	MT_SIGN,	MT_BLACK
	;006 - Venus' World
	.db MT_MOUNTAIN,MT_BLACK,	MT_BLACK,	MT_TOWN,	MT_ROAD,	MT_CAVE,	MT_VINES,	MT_METAL
	.db MT_METAL,	MT_CAVE,	MT_BLACK,	MT_BRICK,	MT_BRICK,	MT_BRICK,	MT_VINES,	MT_VINES
	.db MT_DIRT,	MT_ROAD,	MT_PALMS,	MT_PALM,	MT_GRASS,	MT_CITY,	MT_CITY,	MT_TREES
	.db MT_ROAD,	MT_ROAD,	MT_VOLCANOT,MT_VOLCANO,	MT_VOLCANOL,MT_VOLCANOR,MT_ROAD,	MT_BLACK
	;007 - Shogun's World
	.db MT_MOUNTAIN,MT_BLACK,	MT_BLACK,	MT_TOWN,	MT_GRASS,	MT_WOOD,	MT_VINES,	MT_ROCK
	.db MT_ROCK,	MT_ROCK,	MT_REDROOF,	MT_REDROOF,	MT_BRIDGE,	MT_BRIDGE,	MT_VINES,	MT_VINES
	.db MT_STWALL,	MT_GRASS,	MT_TREES,	MT_STONE,	MT_TOWN,	MT_SHOGUN1,	MT_SHOGUN2,	MT_STWALL
	.db MT_STWALL,	MT_METAL,	MT_METAL,	MT_SHRINE,	MT_BRIDGE,	MT_BRIDGE,	MT_WATER,	MT_WATER
	;008 - Valhalla World
	.db MT_SKY,		MT_BLACK,	MT_BLACK,	MT_SHRINE,	MT_VINES,	MT_BRIDGE,	MT_MOUNTAIN,MT_FLOWERS
	.db MT_TREES,	MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_SKY,		MT_BRIDGE,	MT_BRIDGE,	MT_BLACK
	.db MT_CLOUDS,	MT_CLOUDS,	MT_CLOUDS,	MT_BLACK,	MT_VINES,	MT_SHRINE,	MT_SHRINE,	MT_SHRINE
	.db MT_SHRINE,	MT_SHRINE,	MT_SHRINE,	MT_SHRINE,	MT_VINES,	MT_VINES,	MT_VINES,	MT_CLOUDS
	;009 - Unused, treating as replica of Ashura's World Towns with grass shadows
	.db MT_DIRT,	MT_DIRT,	MT_DIRT,	MT_DOOR,	MT_GRASS,	MT_DIRT,	MT_GRASS,	MT_GRASSHDW
	.db MT_GRASSHDW,MT_BRICK,	MT_BRICK,	MT_BRICK,	MT_SIGN,	MT_SIGN,	MT_SIGN,	MT_SIGN
	.db MT_REDROOF,	MT_HOUSEB,	MT_GRASS,	MT_GRASS,	MT_GRASS,	MT_GRASS,	MT_GRASS,	MT_GRASSHDW
	.db MT_GRASSHDW,MT_BRIDGE,	MT_BRIDGE,	MT_BRIDGE,	MT_ROCK,	MT_ROCK,	MT_DIRT,	MT_DIRT
	;010 - Ki's Body
	.db MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_CAVE,	MT_BLOOD,	MT_BLACK,	MT_BLACK,	MT_BLACK
	.db MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_BLOOD,	MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_OOZE
	.db MT_OOZE,	MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_BLACK
	.db MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_CELLS,	MT_CELLS
	;011 - Town Interior
	.db MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_DOOR,	MT_DOOR,	MT_STAIRS,	MT_STAIRS,	MT_STAIRS
	.db MT_STAIRS,	MT_STAIRS,	MT_STAIRS,	MT_STAIRS,	MT_LAMP,	MT_DOOR,	MT_PLANT,	MT_BRICK
	.db MT_BRICK,	MT_BRICK,	MT_WOOD,	MT_FLOOR,	MT_BARREL,	MT_POT,		MT_SHELF,	MT_SHELF
	.db MT_BED1,	MT_BED2,	MT_TABLE,	MT_CHAIR,	MT_TABLE,	MT_CHAIR,	MT_WINDOW,	MT_BLACK
	;012 - Mr. S' School
	.db MT_BLACK,	MT_BLACK,	MT_WOOD,	MT_DOOR,	MT_DOOR,	MT_STAIRS,	MT_STAIRS,	MT_STAIRS
	.db MT_STAIRS,	MT_STAIRS,	MT_STAIRS,	MT_STAIRS,	MT_STAIRS,	MT_TABLE,	MT_CHAIR,	MT_WOOD
	.db MT_WOOD,	MT_WOOD,	MT_BLACK,	MT_FLOOR,	MT_DIRT,	MT_POT,		MT_SHELF,	MT_SHELF
	.db MT_BED1,	MT_BED2,	MT_BLBOARD,	MT_BLBOARD,	MT_TABLE,	MT_CHAIR,	MT_PLANT,	MT_BLACK
	;013 - Cave
	.db MT_ROCK,	MT_ROCK,	MT_ROCK,	MT_SKY,		MT_ROCK,	MT_GRASS,	MT_GRASS,	MT_STAIRS
	.db MT_STAIRS,	MT_STAIRS,	MT_STAIRS,	MT_STAIRS,	MT_STAIRS,	MT_GRASSHDW,MT_BRIDGE,	MT_ROCK
	.db MT_ROCK,	MT_ROCK,	MT_GRASSHDW,MT_SKY,		MT_GRASS,	MT_GRASS,	MT_GRASS,	MT_GRASS
	.db MT_GRASS,	MT_GRASSHDW,MT_GRASSHDW,MT_PASSAGE,	MT_PASSAGE,	MT_DOOR,	MT_BRIDGE,	MT_BLACK
	;014 - Another Town
	.db MT_GRASS,	MT_BLACK,	MT_BLACK,	MT_DOOR,	MT_GRASS,	MT_STONE,	MT_HOUSEA,	MT_BRIDGE
	.db MT_BRICK,	MT_BRICK,	MT_BRICK,	MT_REDROOF,	MT_SIGN,	MT_SIGN,	MT_SIGN,	MT_SIGN
	.db MT_REDROOF,	MT_HOUSEC,	MT_GRASS,	MT_STONE,	MT_FLOWERS,	MT_TREES,	MT_TREES,	MT_TREES
	.db MT_GRASS,	MT_BRIDGE,	MT_BRIDGE,	MT_PONDWALL,MT_PONDWALL,MT_WATER,	MT_WATER,	MT_WATER
	;015 - Giant Room
	.db MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_CAVE,	MT_BLACK,	MT_BLACK,	MT_UNKNOWN,	MT_REDROOF
	.db MT_REDROOF,	MT_REDROOF,	MT_UNKNOWN,	MT_GWINDOW,	MT_GBED1,	MT_GBED2,	MT_GPILLOW1,MT_GPILLOW2
	.db MT_TILE,	MT_TILE,	MT_GWINDOW,	MT_GWINDOW,	MT_WOOD,	MT_WOOD,	MT_WOOD,	MT_WOOD
	.db MT_WOOD,	MT_WOOD,	MT_BLACK,	MT_BLACK,	MT_BRICK,	MT_BRICK,	MT_BRICK,	MT_BLACK
	;016 - Shop Interior
	.db MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_DOOR,	MT_DOOR,	MT_FLOOR,	MT_FLOOR,	MT_SHELF
	.db MT_COUNTERS,MT_SHELF,	MT_SHELF,	MT_LAMP,	MT_SIGN,	MT_SIGN,	MT_SIGN,	MT_BRICK
	.db MT_BRICK,	MT_BRICK,	MT_WOOD,	MT_FLOOR,	MT_DOOR,	MT_DOOR,	MT_TABLE,	MT_CHAIR
	.db MT_PLANT,	MT_BED1,	MT_BED2,	MT_COUNTER,	MT_COUNTERS,MT_POT,		MT_BARREL,	MT_BLACK
	;017 - Pub Interior
	.db MT_BLACK,	MT_BLACK,	MT_BRICK,	MT_DOOR,	MT_DOOR,	MT_FLOOR,	MT_FLOOR,	MT_SHELF
	.db MT_COUNTERS,MT_BLACK,	MT_SHELF,	MT_SHELF,	MT_LAMP,	MT_POT,		MT_BARREL,	MT_BRICK
	.db MT_BRICK,	MT_BRICK,	MT_WOOD,	MT_FLOOR,	MT_DOOR,	MT_DOOR,	MT_TABLE,	MT_CHAIR
	.db MT_PLANT,	MT_STAIRS,	MT_STAIRS,	MT_COUNTER,	MT_COUNTERS,MT_RECORD1,	MT_RECORD2,	MT_BLACK
	;018 - Giant Store
	.db MT_BLACK,	MT_BLACK,	MT_BRICK,	MT_DOOR,	MT_DOOR,	MT_FLOOR,	MT_FLOOR,	MT_SHELF
	.db MT_COUNTERS,MT_SHELF,	MT_SHELF,	MT_LAMP,	MT_PLANT,	MT_POT,		MT_BARREL,	MT_BRICK
	.db MT_BRICK,	MT_BRICK,	MT_WOOD,	MT_FLOOR,	MT_DOOR,	MT_DOOR,	MT_TABLE,	MT_CHAIR
	.db MT_BLACK,	MT_BED1,	MT_BED2,	MT_COUNTER,	MT_COUNTERS,MT_TABLE,	MT_CHAIR,	MT_BLACK
	;019 - Ki's Shrine
	.db MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_TILE,	MT_STAIRS,	MT_STAIRS,	MT_STAIRS,	MT_STAIRS
	.db MT_STAIRS,	MT_STAIRS,	MT_STAIRS,	MT_STAIRS,	MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_STONE
	.db MT_STONE,	MT_COLUMN,	MT_COLUMN,	MT_TILE,	MT_STATUE,	MT_STATUE,	MT_COLUMN,	MT_COLUMN
	.db MT_KEYTILE,	MT_KEYTILE,	MT_KEYTILE,	MT_KEYTILE,	MT_BLACK,	MT_STAGE,	MT_STAGE,	MT_BLACK
	;020 - Forest Tower Exterior
	.db MT_TREES,	MT_BLACK,	MT_BLACK,	MT_GRASS,	MT_BLACK,	MT_STAIRS,	MT_STAIRS,	MT_STAIRS
	.db MT_STAIRS,	MT_STAIRS,	MT_STAIRS,	MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_BLACK
	.db MT_BRICK,	MT_BRICK,	MT_BRICK,	MT_TILE,	MT_DIRT,	MT_TREES,	MT_TREES,	MT_TREES
	.db MT_FLOOR,	MT_COLUMN,	MT_COLUMN,	MT_GRASS,	MT_TILE,	MT_GRASSHDW,MT_GRASSHDW,MT_BLACK
	;021 - Forest Tower Interior
	.db MT_BLACK,	MT_BLACK,	MT_BRICK,	MT_TILE,	MT_DOOR,	MT_DOOR,	MT_STAIRS,	MT_STAIRS
	.db MT_STAIRS,	MT_STAIRS,	MT_STAIRS,	MT_STAIRS,	MT_STAIRS,	MT_STAIRS,	MT_BLACK,	MT_BRICK
	.db MT_BRICK,	MT_BRICK,	MT_BRICK,	MT_TILE,	MT_DOOR,	MT_DOOR,	MT_PASSAGE,	MT_PASSAGE
	.db MT_FLOOR,	MT_COLUMN,	MT_COLUMN,	MT_BLACK,	MT_BLACK,	MT_GRASSHDW,MT_GRASSHDW,MT_BLACK
	;022 - Forest Tower Interior
	.db MT_BLACK,	MT_BLACK,	MT_BRICK,	MT_DOOR,	MT_DOOR,	MT_STAIRS,	MT_STAIRS,	MT_STAIRS
	.db MT_STAIRS,	MT_STAIRS,	MT_STAIRS,	MT_PASSAGE,	MT_PASSAGE,	MT_OILDRUM,	MT_GARGOYLE,MT_BRICK
	.db MT_BRICK,	MT_BRICK,	MT_BRICK,	MT_FLOOR,	MT_DOOR,	MT_DOOR,	MT_BRICK,	MT_BARREL
	.db MT_TABLE,	MT_CHAIR,	MT_TABLE,	MT_CHAIR,	MT_COUNTER,	MT_COUNTERS,MT_MONITOR,	MT_MONITOR
	;023 - Ashura's Tower
	.db MT_BLACK,	MT_BLACK,	MT_BRICK,	MT_DOOR,	MT_DOOR,	MT_TILE,	MT_STAIRS,	MT_STAIRS
	.db MT_STAIRS,	MT_STAIRS,	MT_STAIRS,	MT_STAIRS,	MT_PASSAGE,	MT_PASSAGE,	MT_BRICK,	MT_BRICK
	.db MT_BRICK,	MT_BRICK,	MT_BRICK,	MT_TILE,	MT_DOOR,	MT_DOOR,	MT_COLUMN,	MT_COLUMN
	.db MT_FLOOR,	MT_SHELF,	MT_SHELF,	MT_JAIL,	MT_STAIRS,	MT_STAIRS,	MT_STAIRS,	MT_DIRT
	;024 - Valhalla Shrine
	.db MT_BLACK,	MT_BLACK,	MT_METAL,	MT_TILE,	MT_DOOR,	MT_DOOR,	MT_STAIRS,	MT_STAIRS
	.db MT_STAIRS,	MT_STAIRS,	MT_STAIRS,	MT_STAIRS,	MT_STONE,	MT_STONE,	MT_STAGE,	MT_METAL
	.db MT_METAL,	MT_GLASS,	MT_GLASS,	MT_TILE,	MT_DOOR,	MT_DOOR,	MT_STONE,	MT_STONE
	.db MT_KEYTILE,	MT_KEYTILE,	MT_KEYTILE,	MT_KEYTILE,	MT_COLUMN,	MT_COLUMN,	MT_STAGE,	MT_STAGE
	;025 - Nasty Dungeon
	.db MT_ROCK,	MT_ROCK,	MT_ROCK,	MT_DIRT,	MT_DOOR,	MT_SKY,		MT_STAIRS,	MT_STAIRS
	.db MT_STAIRS,	MT_STAIRS,	MT_STAIRS,	MT_STAIRS,	MT_STAIRS,	MT_STAIRS,	MT_SKY,		MT_DOOR
	.db MT_ROCK,	MT_ROCK,	MT_CORNERA,	MT_CORNERB,	MT_DIRT,	MT_JAIL,	MT_DIRTSHDW,MT_DIRTSHDW
	.db MT_DIRT,	MT_JAIL,	MT_DIRTSHDW,MT_DIRTSHDW,MT_CAVE,	MT_DIRT,	MT_BLACK,	MT_BLACK
	;026
	.db MT_TREES,	MT_BLACK,	MT_BLACK,	MT_GRASS,	MT_DOOR,	MT_DOOR,	MT_VINES,	MT_TREES
	.db MT_TREES,	MT_TREES,	MT_TREES,	MT_GRASS,	MT_BRICK,	MT_BRICK,	MT_GRASSHDW,MT_GRASSHDW
	.db MT_FLOWERS,	MT_DIRT,	MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_BLACK
	.db MT_BLACK,	MT_BLACK,	MT_PONDWALL,MT_PONDWALL,MT_WATER,	MT_WATER,	MT_WATER,	MT_WATER
	;027 - Venus' World Redux?
	.db MT_MOUNTAIN,MT_BLACK,	MT_BLACK,	MT_TOWN,	MT_ROAD,	MT_CAVE,	MT_VINES,	MT_DIRT
	.db MT_DIRT,	MT_CAVE,	MT_BLACK,	MT_DIRT,	MT_FLOWERS,	MT_DIRT,	MT_VINES,	MT_VINES
	.db MT_DIRT,	MT_ROAD,	MT_PALMS,	MT_PALMS,	MT_GRASS,	MT_CITY,	MT_CITY,	MT_TREES
	.db MT_ROAD,	MT_ROAD,	MT_DIRT,	MT_DIRT,	MT_DIRT,	MT_DIRT,	MT_ROAD,	MT_DUST
	;028 - Hero's House Redux?
	.db MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_DOOR,	MT_DOOR,	MT_STAIRS,	MT_STAIRS,	MT_STAIRS
	.db MT_STAIRS,	MT_STAIRS,	MT_STAIRS,	MT_STAIRS,	MT_LAMP,	MT_DOOR,	MT_PLANT,	MT_BRICK
	.db MT_BRICK,	MT_BRICK,	MT_WOOD,	MT_FLOOR,	MT_BARREL,	MT_POT,		MT_SHELF,	MT_SHELF
	.db MT_BED1,	MT_BED2,	MT_TABLE,	MT_CHAIR,	MT_TABLE,	MT_CHAIR,	MT_WINDOW,	MT_BLACK
	;029 - Interior
	.db MT_BLACK,	MT_BLACK,	MT_METAL,	MT_FLOOR,	MT_DOOR,	MT_DOOR,	MT_STAIRS,	MT_STAIRS
	.db MT_STAIRS,	MT_STAIRS,	MT_STAIRS,	MT_STAIRS,	MT_STAIRS,	MT_STAIRS,	MT_JAIL,	MT_METAL
	.db MT_METAL,	MT_METAL,	MT_FLOOR,	MT_FLOOR,	MT_DOOR,	MT_DOOR,	MT_METAL,	MT_OILDRUM
	.db MT_STOOL,	MT_TABLE,	MT_BED1,	MT_BED2,	MT_COUNTER,	MT_COUNTERS,MT_MONITOR,	MT_MONITOR
	;030 - Interior but broken
	.db MT_BLACK,	MT_BLACK,	MT_METAL,	MT_FLOOR,	MT_DOOR,	MT_DOOR,	MT_STAIRS,	MT_STAIRS
	.db MT_STAIRS,	MT_STAIRS,	MT_STAIRS,	MT_STAIRS,	MT_STAIRS,	MT_STAIRS,	MT_JAIL,	MT_METAL
	.db MT_METAL,	MT_METAL,	MT_FLOOR,	MT_FLOOR,	MT_DOOR,	MT_DOOR,	MT_METAL,	MT_OILDRUM
	.db MT_STOOL,	MT_TABLE,	MT_BED1,	MT_BED2,	MT_COUNTER,	MT_COUNTERS,MT_MONITOR,	MT_MONITOR
	;031 - Busted up house (Map 91)
	.db MT_BLACK,	MT_BLACK,	MT_WOOD,	MT_DOOR,	MT_DOOR,	MT_FLOOR,	MT_FLOOR,	MT_SHELF
	.db MT_FLOOR,	MT_BRIDGE,	MT_SHELF,	MT_SHELF,	MT_LAMP,	MT_FLOOR,	MT_FLOOR,	MT_WOOD
	.db MT_WOOD,	MT_WOOD,	MT_WOOD,	MT_FLOOR,	MT_DOOR,	MT_DOOR,	MT_TABLE,	MT_FLOOR
	.db MT_FLOOR,	MT_STAIRS,	MT_STAIRS,	MT_WOOD,	MT_FLOOR,	MT_RECORD1,	MT_RECORD2,	MT_BLACK
	;032 - Venus' Castle
	.db MT_BLACK,	MT_BLACK,	MT_METAL,	MT_TILE,	MT_DOOR,	MT_DOOR,	MT_STAIRS,	MT_STAIRS
	.db MT_STAIRS,	MT_STAIRS,	MT_COLUMN,	MT_COLUMN,	MT_DOOR,	MT_DOOR,	MT_FLOOR,	MT_METAL
	.db MT_METAL,	MT_METAL,	MT_METAL,	MT_TILE,	MT_GLASS,	MT_GLASS,	MT_COLUMN,	MT_COLUMN
	.db MT_DIRT,	MT_WOOD,	MT_STONE,	MT_DIRT,	MT_STOOL,	MT_COLUMN,	MT_STAGE,	MT_STAGE
	;033 - Venus' City
	.db MT_CITY,	MT_BLACK,	MT_BLACK,	MT_CITY,	MT_BLACK,	MT_GLASS,	MT_GLASS,	MT_GLASS
	.db MT_GLASS,	MT_CITY,	MT_CITY,	MT_CITY,	MT_BRICK,	MT_BRICK,	MT_CITY,	MT_TREES
	.db MT_CITY,	MT_CITY,	MT_CITY,	MT_ROAD,	MT_GLASS,	MT_GLASS,	MT_CITY,	MT_ROAD
	.db MT_ROAD,	MT_ROAD,	MT_ROAD,	MT_ROAD,	MT_ROAD,	MT_ROAD,	MT_BRIDGE,	MT_BRIDGE
	;034
	.db MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_DOOR,	MT_DOOR,	MT_STAIRS,	MT_STAIRS,	MT_STAIRS
	.db MT_STAIRS,	MT_STAIRS,	MT_STAIRS,	MT_LAMP,	MT_SIGN,	MT_SIGN,	MT_SIGN,	MT_BRICK
	.db MT_BRICK,	MT_BRICK,	MT_WOOD,	MT_FLOOR,	MT_DOOR,	MT_DOOR,	MT_TABLE,	MT_STOOL
	.db MT_POT,		MT_PLANT,	MT_COUNTER,	MT_COUNTERS,MT_RECORD1,	MT_RECORD2,	MT_MONITOR,	MT_MONITOR
	;035
	.db MT_TREES,	MT_BLACK,	MT_WOOD,	MT_DOOR,	MT_GRASS,	MT_DIRT,	MT_BLACK,	MT_FLOOR
	.db MT_ROCK,	MT_ROCK,	MT_ROCK,	MT_FLOOR,	MT_PASSAGE,	MT_PASSAGE,	MT_SIGN,	MT_SIGN
	.db MT_WOOD,	MT_WOOD,	MT_GRASS,	MT_DIRT,	MT_FLOWERS,	MT_TREES,	MT_PALMS,	MT_POT
	.db MT_BRIDGE,	MT_WOOD,	MT_COUNTERS,MT_BED1,	MT_BED2,	MT_TABLE,	MT_STOOL,	MT_BLACK
	;036
	.db MT_BLACK,	MT_BLACK,	MT_ROCK,	MT_SKY,		MT_ROCK,	MT_DIRT,	MT_CAVE,	MT_STAIRS
	.db MT_STAIRS,	MT_STAIRS,	MT_STAIRS,	MT_STAIRS,	MT_STAIRS,	MT_STAIRS,	MT_STAIRS,	MT_ROCK
	.db MT_ROCK,	MT_ROCK,	MT_ROCK,	MT_SKY,		MT_DIRT,	MT_LAVA,	MT_LAVA,	MT_PASSAGE
	.db MT_PASSAGE,	MT_ROCK,	MT_CAVE,	MT_ROCK,	MT_CAVE,	MT_BRIDGE,	MT_BRIDGE,	MT_LAVA
	;037 - Venus Gate
	.db MT_GRASS,	MT_BLACK,	MT_BLACK,	MT_GRASS,	MT_STAIRS,	MT_STAIRS,	MT_STAIRS,	MT_STAIRS
	.db MT_STAIRS,	MT_STAIRS,	MT_STAIRS,	MT_STAIRS,	MT_BLACK,	MT_WOOD,	MT_WOOD,	MT_BRICK
	.db MT_BRICK,	MT_BRICK,	MT_BLACK,	MT_GRASS,	MT_DIRTSHDW,MT_DIRTSHDW,MT_PATH,	MT_TREES
	.db MT_PALMS,	MT_DIRT,	MT_FLOWERS,	MT_BLACK,	MT_PASSAGE,	MT_PASSAGE,	MT_BRICK,	MT_BLACK
	;038
	.db MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_SKY,		MT_FLOOR,	MT_PATH,	MT_DOOR,	MT_STAIRS
	.db MT_STAIRS,	MT_STAIRS,	MT_STAIRS,	MT_STAIRS,	MT_STAIRS,	MT_STAIRS,	MT_STAIRS,	MT_FLOOR
	.db MT_FLOOR,	MT_BRICK,	MT_BRICK,	MT_SKY,		MT_PATH,	MT_WATER,	MT_CAVE,	MT_PONDWALL
	.db MT_PONDWALL,MT_WATER,	MT_WATER,	MT_JAIL,	MT_BRIDGE,	MT_BRIDGE,	MT_BRIDGE,	MT_WATER
	;039 - Race track
	.db MT_GRASS,	MT_BLACK,	MT_BLACK,	MT_ROAD,	MT_BLACK,	MT_ROAD,	MT_ROAD,	MT_OILDRUM
	.db MT_TREES,	MT_TREES,	MT_TREES,	MT_GRASS,	MT_PATH,	MT_FENCE,	MT_ROAD,	MT_BLACK
	.db MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_BLACK
	.db MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_BLACK
	;040 - Apollo's Shrine
	.db MT_BLACK,	MT_BLACK,	MT_LAMP,	MT_STAIRS,	MT_STAIRS,	MT_STAIRS,	MT_STAIRS,	MT_STAIRS
	.db MT_STAIRS,	MT_STAIRS,	MT_STAIRS,	MT_STAIRS,	MT_BLACK,	MT_WOOD,	MT_WOOD,	MT_LAMP
	.db MT_LAMP,	MT_GLASS,	MT_GLASS,	MT_TILE,	MT_TILE,	MT_STONE,	MT_COLUMN,	MT_COLUMN
	.db MT_KEYTILE,	MT_KEYTILE,	MT_KEYTILE,	MT_KEYTILE,	MT_STONE,	MT_STAGE,	MT_STAGE,	MT_BLACK
	;041
	.db MT_ROCK,	MT_ROCK,	MT_ROCK,	MT_SKY,		MT_STAIRS,	MT_STAIRS,	MT_STAIRS,	MT_STAIRS
	.db MT_STAIRS,	MT_STAIRS,	MT_STAIRS,	MT_STAIRS,	MT_SKY,		MT_BRIDGE,	MT_BRIDGE,	MT_ROCK
	.db MT_ROCK,	MT_ROCK,	MT_ROCK,	MT_DIRT,	MT_DIRTSHDW,MT_DIRTSHDW,MT_BLACK,	MT_BLACK
	.db MT_BLACK,	MT_DIRTSHDW,MT_PASSAGE,	MT_PASSAGE,	MT_DIRTSHDW,MT_ROCK,	MT_CAVE,	MT_BLACK
	;042 - Undersea Volcano
	.db MT_BLACK,	MT_BLACK,	MT_ROCK,	MT_SKY,		MT_ROCK,	MT_DIRT,	MT_CAVE,	MT_ROCK
	.db MT_ROCK,	MT_ROCK,	MT_ROCK,	MT_ROCK,	MT_ROCK,	MT_ROCK,	MT_ROCK,	MT_ROCK
	.db MT_ROCK,	MT_ROCK,	MT_ROCK,	MT_SKY,		MT_DIRT,	MT_LAVA,	MT_BLACK,	MT_PASSAGE
	.db MT_PASSAGE,	MT_ROCK,	MT_CAVE,	MT_ROCK,	MT_CAVE,	MT_STONE,	MT_STONE,	MT_LAVA
	;043 - Unused map?
	.db MT_BLACK,	MT_BLACK,	MT_CRYSTAL,	MT_SKY,		MT_CRYSTAL,	MT_BLACK,	MT_CAVE,	MT_STAIRS
	.db MT_STAIRS,	MT_STAIRS,	MT_STAIRS,	MT_STAIRS,	MT_STAIRS,	MT_STAIRS,	MT_STAIRS,	MT_CRYSTAL
	.db MT_CRYSTAL,	MT_CRYSTAL,	MT_MOON,	MT_SKY,		MT_BRIDGE,	MT_BRIDGE,	MT_PASSAGE,	MT_PASSAGE
	.db MT_MOON,	MT_BLACK,	MT_MOON,	MT_MOON,	MT_CRYSTAL,	MT_CAVE,	MT_BLACK,	MT_BLACK
	;044 - Unused map?
	.db MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_SKY,		MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_BLACK
	.db MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_SKY,		MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_BLACK
	.db MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_BLACK
	.db MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_BLACK
	;045 - Another town
	.db MT_GRASS,	MT_BLACK,	MT_REDROOF,	MT_DOOR,	MT_GRASS,	MT_PATH,	MT_DIRT,	MT_FENCE
	.db MT_BRICK,	MT_BRICK,	MT_BRICK,	MT_HOUSEA,	MT_SIGN,	MT_SIGN,	MT_SIGN,	MT_SIGN
	.db MT_REDROOF,	MT_HOUSEB,	MT_GRASS,	MT_PATH,	MT_FLOWERS,	MT_TREES,	MT_TREES,	MT_TREES
	.db MT_BRIDGE,	MT_BRIDGE,	MT_BRIDGE,	MT_PONDWALL,MT_PONDWALL,MT_WATER,	MT_WATER,	MT_WATER
	;046 - Barn?
	.db MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_DOOR,	MT_DOOR,	MT_DOOR,	MT_DOOR,	MT_BLACK
	.db MT_BLACK,	MT_FENCE,	MT_BLACK,	MT_SHELF,	MT_SHELF,	MT_POT,		MT_BARREL,	MT_WOOD
	.db MT_WOOD,	MT_WOOD,	MT_GRASS,	MT_FLOOR,	MT_DIRT,	MT_WINDOW,	MT_TABLE,	MT_STOOL
	.db MT_TABLE,	MT_STAIRS,	MT_STAIRS,	MT_COUNTER,	MT_COUNTERS,MT_STOOL,	MT_BLACK,	MT_BLACK
	;047 - Churchy shrine thing
	.db MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_FLOOR,	MT_DOOR,	MT_DOOR,	MT_DOOR,	MT_DOOR
	.db MT_STAGE,	MT_STAGE,	MT_BLACK,	MT_BLACK,	MT_TABLE,	MT_STOOL,	MT_POT,		MT_BRICK
	.db MT_BRICK,	MT_STONE,	MT_STONE,	MT_FLOOR,	MT_FLOOR,	MT_PLANT,	MT_COLUMN,	MT_COLUMN
	.db MT_TILE,	MT_TILE,	MT_TILE,	MT_TILE,	MT_WOOD,	MT_WOOD,	MT_BLACK,	MT_BLACK
	;048 - Shogun Castle
	.db MT_GRASS,	MT_BLACK,	MT_REDROOF,	MT_DOOR,	MT_WOOD,	MT_REDROOF,	MT_STONE,	MT_BRIDGE
	.db MT_BRIDGE,	MT_REDROOF,	MT_PONDWALL,MT_PONDWALL,MT_WATER,	MT_WATER,	MT_REDROOF,	MT_REDROOF
	.db MT_REDROOF,	MT_REDROOF,	MT_STWALL,	MT_GRASS,	MT_TREES,	MT_GRASSHDW,MT_GRASSHDW,MT_FLOOR
	.db MT_SUPPORTG,MT_BRIDGE,	MT_STWALL2,	MT_STONE,	MT_STONE,	MT_ROCK,	MT_WATER,	MT_WATER
	;049 - Shogun Castle Roof
	.db MT_BLACK,	MT_BLACK,	MT_REDROOF,	MT_STWALL2,	MT_STONE,	MT_TATAMI,	MT_TATAMI,	MT_STAIRS
	.db MT_STAIRS,	MT_STAIRS,	MT_STAIRS,	MT_STAIRS,	MT_STAIRS,	MT_BARREL,	MT_POT,		MT_REDROOF
	.db MT_REDROOF,	MT_STWALL2,	MT_STONE,	MT_TATAMI,	MT_TATAMI,	MT_FLOOR,	MT_STONE,	MT_STONE
	.db MT_PLANT,	MT_BLOCK,	MT_TABLE,	MT_BEDB1,	MT_BEDB2,	MT_STWALL2,	MT_STONE,	MT_BLACK
	;050
	.db MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_REDROOF,	MT_REDROOF,	MT_REDROOF,	MT_BLACK,	MT_BLACK
	.db MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_BLACK
	.db MT_METAL,	MT_REDROOF,	MT_METAL,	MT_METAL,	MT_METAL,	MT_METAL,	MT_MOON,	MT_TOWN
	.db MT_REDROOF,	MT_REDROOF,	MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_STARSB
	;051 - Shogun Town Interior
	.db MT_BLACK,	MT_BLACK,	MT_REDROOF,	MT_TATAMI,	MT_DOOR,	MT_STONE,	MT_STWALL2,	MT_BRIDGE
	.db MT_BRIDGE,	MT_BRIDGE,	MT_BRIDGE,	MT_STONE,	MT_SHELF,	MT_SHELF,	MT_BLOCK,	MT_REDROOF
	.db MT_REDROOF,	MT_STWALL2,	MT_STONE,	MT_TATAMI,	MT_TATAMI,	MT_FLOOR,	MT_STWALL2,	MT_DOOR
	.db MT_STONE,	MT_WOOD,	MT_POT,		MT_BARREL,	MT_TABLE,	MT_STOOL,	MT_PLANT,	MT_BLACK
	;052 - Shogun Court
	.db MT_GRASS,	MT_BLACK,	MT_BLACK,	MT_DIRT,	MT_DOOR,	MT_STONE,	MT_BRIDGE,	MT_DIRT
	.db MT_STWALL,	MT_STONE,	MT_REDROOF,	MT_REDROOF,	MT_PLANT,	MT_STAIRS,	MT_STWALL2,	MT_REDROOF
	.db MT_REDROOF,	MT_STWALL2,	MT_STONE,	MT_TATAMI,	MT_TATAMI,	MT_FLOOR,	MT_DOOR,	MT_STONE
	.db MT_SHELF,	MT_SHELF,	MT_POT,		MT_BARREL,	MT_SUPPORTD,MT_BLOCK,	MT_PLANT,	MT_BLACK
	;053 - Shogun Town Interior
	.db MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_FLOOR,	MT_DOOR,	MT_STWALL2,	MT_BLACK,	MT_WINDOW
	.db MT_WOOD,	MT_WOOD,	MT_STONE,	MT_PLANT,	MT_BLBOARD,	MT_BLBOARD,	MT_STWALL2,	MT_REDROOF
	.db MT_REDROOF,	MT_STWALL2,	MT_STONE,	MT_TATAMI,	MT_TATAMI,	MT_FLOOR,	MT_TABLE,	MT_STOOL
	.db MT_SHELF,	MT_SHELF,	MT_POT,		MT_BARREL,	MT_BEDB1,	MT_BEDB2,	MT_BLOCK,	MT_BLACK
	;054 - Shogun Jail
	.db MT_BLACK,	MT_BLACK,	MT_WOOD,	MT_BRIDGE,	MT_BRIDGE,	MT_BRIDGE,	MT_DOOR,	MT_BRIDGE
	.db MT_BRIDGE,	MT_BRIDGE,	MT_BRIDGE,	MT_BRIDGE,	MT_WOOD,	MT_WOOD,	MT_WOOD,	MT_WOOD
	.db MT_FLOOR,	MT_FLOOR,	MT_FLOOR,	MT_FLOOR,	MT_JAIL,	MT_TABLE,	MT_STOOL,	MT_POT
	.db MT_BARREL,	MT_BRIDGE,	MT_BRIDGE,	MT_BRIDGE,	MT_WATER,	MT_WATER,	MT_WATER,	MT_WATER
	;055 - Shogun Town
	.db MT_GRASS,	MT_BLACK,	MT_REDROOF,	MT_DOOR,	MT_GRASS,	MT_REDROOF,	MT_REDROOF,	MT_REDROOF
	.db MT_REDROOF,	MT_BRIDGE,	MT_STONE,	MT_ROCK,	MT_SIGN,	MT_SIGN,	MT_SIGN,	MT_SIGN
	.db MT_REDROOF,	MT_REDROOF,	MT_STONE,	MT_STWALL,	MT_GRASS,	MT_TREES,	MT_FLOWERS,	MT_FENCE
	.db MT_BRIDGE,	MT_BRIDGE,	MT_BRIDGE,	MT_PONDWALL,MT_PONDWALL,MT_WATER,	MT_WATER,	MT_WATER
	;056 - Shogun Town Interior
	.db MT_BLACK,	MT_BLACK,	MT_REDROOF,	MT_STWALL2,	MT_STONE,	MT_DOOR,	MT_WOOD,	MT_BRIDGE
	.db MT_STWALL2,	MT_SHELF,	MT_SHELF,	MT_BLOCK,	MT_SIGN,	MT_SIGN,	MT_SIGN,	MT_REDROOF
	.db MT_REDROOF,	MT_STONE,	MT_TATAMI,	MT_TATAMI,	MT_FLOOR,	MT_PLANT,	MT_STONE,	MT_TABLE
	.db MT_STOOL,	MT_BEDB1,	MT_BEDB2,	MT_POT,		MT_DIRT,	MT_RECORD1,	MT_RECORD2,	MT_BLACK
	;057 - Vine
	.db MT_BLACK,	MT_BLACK,	MT_VINES,	MT_SKY,		MT_VINES,	MT_DIRT,	MT_CAVE,	MT_STAIRS
	.db MT_STAIRS,	MT_STAIRS,	MT_STAIRS,	MT_STAIRS,	MT_STAIRS,	MT_STAIRS,	MT_STAIRS,	MT_VINES
	.db MT_VINES,	MT_DIRTSHDW,MT_DIRT,	MT_SKY,		MT_DIRTSHDW,MT_BLACK,	MT_BLACK,	MT_BLACK
	.db MT_BLACK,	MT_BLACK,	MT_PASSAGE,	MT_PASSAGE,	MT_VINES,	MT_CAVE,	MT_VINES,	MT_VINES
	;058 - Vineworld
	.db MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_DOOR,	MT_DOOR,	MT_CRYSTALW,MT_CRYSTAL,	MT_STAIRS
	.db MT_STAIRS,	MT_STAIRS,	MT_STAIRS,	MT_BLACK,	MT_CRYSTAL,	MT_STARSA,	MT_STARSB,	MT_SIGN
	.db MT_SIGN,	MT_SIGN,	MT_STAGE,	MT_STAGE,	MT_DOOR,	MT_DOOR,	MT_BLACK,	MT_BLACK
	.db MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_BLACK
	;059 - Vineworld
	.db MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_VINES,	MT_STAGE,	MT_SHRINE,	MT_BLACK,	MT_BLACK
	.db MT_BLACK,	MT_BLACK,	MT_ROCK,	MT_ROCK,	MT_CRYSTAL,	MT_BRIDGE,	MT_BRIDGE,	MT_BRIDGE
	.db MT_VINES,	MT_VINES,	MT_VINES,	MT_VINES,	MT_SHRINE,	MT_SHRINE,	MT_SHRINE,	MT_SHRINE
	.db MT_SHRINE,	MT_SHRINE,	MT_BLACK,	MT_BLACK,	MT_SHRINE,	MT_SHRINE,	MT_BLACK,	MT_STARSB
	;060 - Venus
	.db MT_BLACK,	MT_BLACK,	MT_CRYSTAL,	MT_TILE,	MT_TILE,	MT_CRYSTAL,	MT_DOOR,	MT_BLACK
	.db MT_DOOR,	MT_BRIDGE,	MT_CRYSTALW,MT_MOON,	MT_STAIRS,	MT_STAIRS,	MT_STAIRS,	MT_CRYSTAL
	.db MT_CRYSTAL,	MT_COLUMN,	MT_COLUMN,	MT_TILE,	MT_TILE,	MT_COLUMN,	MT_COLUMN,	MT_KEYTILE
	.db MT_KEYTILE,	MT_KEYTILE,	MT_KEYTILE,	MT_STARSB,	MT_STARSB,	MT_STAGE,	MT_STAGE,	MT_STARSB
	;061 - Shogun Dock
	.db MT_GRASS,	MT_BLACK,	MT_BLACK,	MT_BRIDGE,	MT_BRIDGE,	MT_BRIDGE,	MT_GRASS,	MT_BLACK
	.db MT_FENCE,	MT_REDROOF,	MT_STONE,	MT_ROCK,	MT_ROCK,	MT_ROCK,	MT_REDROOF,	MT_REDROOF
	.db MT_REDROOF,	MT_REDROOF,	MT_STWALL,	MT_GRASS,	MT_TREES,	MT_BRIDGE,	MT_BRIDGE,	MT_BRIDGE
	.db MT_GRASSHDW,MT_GRASSHDW,MT_PONDWALL,MT_PONDWALL,MT_WATER,	MT_WATER,	MT_WATER,	MT_WATER
	;062 - Vine Stairs
	.db MT_BLACK,	MT_BLACK,	MT_BRICK,	MT_DOOR,	MT_DOOR,	MT_TILE,	MT_SKY,		MT_SKY
	.db MT_VINES,	MT_VINES,	MT_VINES,	MT_VINES,	MT_BRIDGE,	MT_VINES,	MT_SKY,		MT_CRYSTAL
	.db MT_CRYSTAL,	MT_ROCK,	MT_ROCK,	MT_TILE,	MT_DOOR,	MT_DOOR,	MT_BRIDGE,	MT_BRIDGE
	.db MT_BRIDGE,	MT_BRIDGE,	MT_BRIDGE,	MT_BRIDGE,	MT_BRIDGE,	MT_BRIDGE,	MT_BRIDGE,	MT_STARSB
	;063 - Hecka Vine Town
	.db MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_CRYSTAL,	MT_METAL,	MT_DOOR,	MT_STARSB,	MT_CRYSTAL
	.db MT_ROCK,	MT_ROCK,	MT_TILE,	MT_DOOR,	MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_BLACK
	.db MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_METAL,	MT_BLACK,	MT_BLACK,	MT_BLACK
	.db MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_BLACK,	MT_STARSA,	MT_STARSB,	MT_VINES,	MT_VINES
MetatileAttrEnd:
.ENDS

